//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriviaQuiz.Properties {
    using System;
    using System.IO;
    using System.Text;


    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TriviaQuiz.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_right {
            get {
                object obj = ResourceManager.GetObject("Arrow_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap board {
            get {
                object obj = ResourceManager.GetObject("board", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amazon(T)
        ///eBay
        ///Overstock
        ///Shopify
        ///Four Years
        ///Year(T)
        ///Two Years
        ///Eight Years
        ///1998
        ///1999
        ///2000(T)
        ///2001
        ///Hard Disk Drive
        ///Central Processing Unit
        ///Graphics Processing Unit
        ///Motherboard(T)
        ///C#(T)
        ///Java
        ///C++
        ///Objective-C
        ///Paint.NET
        ///Inkscape(T)
        ///GIMP
        ///Adobe Photoshop
        ///Taiwan(T)
        ///United States
        ///Germany
        ///China 
        ///The Only Router
        ///The Orange Router
        ///The Onion Router(T)
        ///The Ominous Router
        ///December 17, 1996
        ///November 12, 1990
        ///November 24, 1995
        ///December 20, 1990(T)
        ///Content Distribution Network
        ///Content Delivery Network(T)
        ///Computational Data Ne [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ComputerScienceAnswers {
            get {
                //return ResourceManager.GetString("ComputerScienceAnswers", resourceCulture);
                return File.ReadAllText(@"..\..\Resources\ComputerScienceAnswers.txt", Encoding.UTF8);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What was William Frederick Cody better known as?
        ///Moore&apos;s law originally stated that the number of transistors on a microprocessor chip would double every...
        ///When was the programming language C# released?
        ///On which computer hardware device is the BIOS chip located?
        ///Which of the following languages is used as a scripting language in the Unity 3D game engine?
        ///All of the following programs are classified as raster graphics editors EXCEPT:
        ///The computer OEM manufacturer Clevo, known for its Sager notebook line, is [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ComputerScienceQuestions {
            get {
                //return ResourceManager.GetString("ComputerScienceQuestions", resourceCulture);
                return File.ReadAllText(@"..\..\Resources\ComputerScienceQuestions.txt", Encoding.UTF8);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cultr {
            get {
                object obj = ResourceManager.GetObject("cultr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap geography {
            get {
                object obj = ResourceManager.GetObject("geography", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Africa
        ///Euroe
        ///Antartica
        ///Asia(T)
        ///Bolivia
        ///Ecuador
        ///Chile(T)
        ///Peru
        ///Canada(T)
        ///USA
        ///Australia
        ///India
        ///Atacam desert
        ///Sahara desert
        ///Kufra, Libiya
        ///Mcmurdo, Antartica(T)
        ///Egypt
        ///Algeria
        ///Sudan(T)
        ///Libya
        ///Jerusalem
        ///Damascus(T)
        ///Jericho
        ///Athens
        ///Australia(T)
        ///South America
        ///Antartica
        ///Africa
        ///Argentina
        ///Brazil(T)
        ///Peru
        ///Columbia
        ///Kilimanjaro
        ///Mount Everest(T)
        ///Aconcagua
        ///Qogir
        ///Nauru
        ///Grenada
        ///Monaco
        ///Vatican City(T)
        ///Java trench
        ///Mariana trench(T)
        ///Tonga trench
        ///Eurasian basin
        ///Lebanon
        ///Egypt
        ///Moroco(T)
        ///Syria
        ///Paraguay
        ///Uruguay(T)
        ///Suriname
        ///Peru
        ///Australia [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string GeographyAnwsers {
            get {
                //return ResourceManager.GetString("GeographyAnwsers", resourceCulture);
                return File.ReadAllText(@"..\..\Resources\GeographyAnwsers.txt", Encoding.UTF8);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What is Earth&apos;s largest continent?
        ///What razor-thin country accounts for more than half of the western coastline of South America?
        ///What country has the most natural lakes?
        ///What is the driest place on Earth?
        ///Which African nation has the most pyramids?
        ///What is the oldest city in the world?
        ///What is the flattest continent?
        ///What is the largest country in South America?
        ///What is the tallest mountain in the world?
        ///What is the smallest independent country on Earth?
        ///What is the deepest point in Earth&apos;s oceans?
        ///Along w [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string GeographyQuestions {
            get {
                //return ResourceManager.GetString("GeographyQuestions", resourceCulture);
                return File.ReadAllText(@"..\..\Resources\GeographyQuestions.txt", Encoding.UTF8);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iStock_636447976 {
            get {
                object obj = ResourceManager.GetObject("iStock_636447976", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap J4GYui_home_round_button_icon_png {
            get {
                object obj = ResourceManager.GetObject("J4GYui_home_round_button_icon_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NSTU {
            get {
                object obj = ResourceManager.GetObject("NSTU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ag(T)
        ///Au
        ///Ca
        ///Mg
        ///Earth
        ///Mercury
        ///Venus(T)
        ///Mars
        ///500g
        ///100g
        ///1kg
        ///250g(T)
        ///A+
        ///B-
        ///0
        ///AB-
        ///1billion years
        ///5billion years(T)
        ///6billion years
        ///3billion years
        ///Canada(T)
        ///USA
        ///Rusia
        ///Brazil
        ///Exosphere
        ///Stratosphere
        ///Troposphere(T)
        ///Neosphere
        ///Venus
        ///Mercury(T)
        ///Earth 
        ///Mars
        ///200
        ///205
        ///206(T)
        ///196
        ///1791
        ///1942
        ///450 B.C.(T)
        ///1050
        ///12 months
        ///16 months
        ///8 months(T)
        ///4 month
        ///Tounge
        ///Cheek
        ///All of these(T)
        ///Esophagus
        ///Saturn
        ///Uranus
        ///Mars
        ///Juptier(T)
        ///Parrot
        ///Crane
        ///Sparrow
        ///Finch(T)
        ///Altimeter
        ///Anemometer(T)
        ///Fanometer
        ///Barometer
        ///Rhinoceros
        ///Neandherthal(T)
        ///Gorilla
        ///Huma [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string NSTUAnwsers {
            get {
               // return ResourceManager.GetString("NSTUAnwsers", resourceCulture);
                return File.ReadAllText(@"..\..\Resources\NSTUAnwsers.txt", Encoding.UTF8);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What is the symbol for Silver?
        ///Which is the hottest planet in the solar system?
        ///How much salt does the average human body contain? 
        ///Which is the rarest blood type in humans?
        ///How old is our Sun?
        ///Which country has the longest coastline?
        ///What is the name of the layer of air closest to us in the atmosphere?
        ///Which planet is closest to the sun? 
        ///How many bones are there in the human body?
        ///When was the idea of the atom first introduced?
        ///What is the gestation period of a Hippopotamus?
        ///Where are your taste buds loca [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string NSTUQuestions {
            get {
               // return ResourceManager.GetString("NSTUQuestions", resourceCulture);
                return File.ReadAllText(@"..\..\Resources\NSTUQuestions.txt", Encoding.UTF8);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Piers Brosnan
        ///Timothy Dalton
        ///Daniel Craig(T)
        ///Shawn Conery
        ///Kourney(T)
        ///Kim
        ///Khole
        ///Kendall
        ///The Empire Strikes Back
        ///The Phantom Menace(T)
        ///The Return of the Jedi
        ///The Last Jedi
        ///Mellman
        ///Morty
        ///Mamy
        ///Manny(T)
        ///Johnny Depp(T)
        ///Brad Pit
        ///Tom Hiddelstone
        ///Ben Affleck
        ///The Pricne of Pop
        ///The king od Music
        ///The King of Pop(T)
        ///The Best there ever was
        ///Queen Victoria
        ///Princess Diana(T)
        ///Queen Elizabeth II
        ///Prince Charles
        ///1970
        ///1989(T)
        ///1995
        ///1973
        ///Prohibition(T)
        ///Piety
        ///Abstinence
        ///Aversion
        ///1995
        ///1960
        ///1945(T)
        ///1942
        ///Edwin Aldrin
        ///Michael Collins
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string PopCultureAnswers {
            get {
                //return ResourceManager.GetString("PopCultureAnswers", resourceCulture);
                return File.ReadAllText(@"..\..\Resources\PopCultureAnswers.txt", Encoding.UTF8);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Which actor made his debut as James Bond in the film Casino Royale in 2006?
        ///Who is the oldest of the Kardashian sisters?
        ///The character Jar Jar Binks first appears in which of the Star Wars movies?
        ///In the Ice Age movies, what is the name of the woolly mammoth?
        ///Which actor plays the role of Captain Jack Sparrow in the Pirates of the Caribbean movies?
        ///What was Michael Jackson known as?
        ///Which member of the British Royal Family passed away in a car crash?
        ///When did the Berlin wall come down?
        ///What was the American [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string PopCultureQuestions {
            get {
                //return ResourceManager.GetString("PopCultureQuestions", resourceCulture);
                return File.ReadAllText(@"..\..\Resources\PopCultureQuestions.txt", Encoding.UTF8);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rotate {
            get {
                object obj = ResourceManager.GetObject("rotate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rotate1 {
            get {
                object obj = ResourceManager.GetObject("rotate1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Site_Background {
            get {
                object obj = ResourceManager.GetObject("Site_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap small_clipart_tiny_17 {
            get {
                object obj = ResourceManager.GetObject("small_clipart_tiny_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sport {
            get {
                object obj = ResourceManager.GetObject("sport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New York Knicks(T)
        ///New Orleans Pelicans
        ///Los Angeles Lakers
        ///Atlanta Hawks
        ///Chelsea
        ///Real Madrid(T)
        ///Barcelona
        ///Manchester City
        ///1
        ///4
        ///6(T)
        ///0
        ///Michael Phleps
        ///Usain Bolt(T)
        ///Goran Pandev
        ///Asafa Powel
        ///Ferrari(T)
        ///Mercedes
        ///Lotus
        ///Red Bull
        ///Chelsea
        ///Arsenal(T)
        ///Liverpool
        ///Macnhester United
        ///Germany
        ///Italy
        ///Brazil(T)
        ///France
        ///Matt Buiondi
        ///Mark Spitz
        ///Ian Thorpe
        ///Michale Phelps(T)
        ///Kobe Bryant
        ///Michale Jordan
        ///Wilt Chamberlain(T)
        ///Lebron James
        ///Vardar(T)
        ///Metalurg
        ///Eurofarm Rabotnik
        ///Pelister
        ///65
        ///43
        ///82(T)
        ///71
        ///Russia(T)
        ///Canada
        ///USA
        ///Finland
        ///France
        ///Ge [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string SportsAnwsers {
            get {
               // return ResourceManager.GetString("SportsAnwsers", resourceCulture);
                return File.ReadAllText(@"..\..\Resources\SportsAnwsers.txt", Encoding.UTF8);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Which team is the oldest nba team?
        ///Which european team has won the most Champions league trophies?
        ///How many NBA championships has Michael Jordan won?
        ///Who holds the world record for 100m sprint in the male category?
        ///Which team did Michael Schumacher drive for?
        ///Which team has won the only golden Premier League trophy?
        ///Which country has the most world cup trophies in football?
        ///Which male swimmer has the most gold medals in Olympics history?
        ///Who has scored the most points in an NBA game?
        ///Which macedonian team h [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string SportsQuestions {
            get {
               // return ResourceManager.GetString("SportsQuestions", resourceCulture);
                return File.ReadAllText(@"..\..\Resources\SportsQuestions.txt", Encoding.UTF8);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trivia_quiz_logo {
            get {
                object obj = ResourceManager.GetObject("trivia_quiz_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WheelFINAL {
            get {
                object obj = ResourceManager.GetObject("WheelFINAL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
